name: CI
on: [push]
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} tests
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7, jruby-9.3]
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Setup ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: ./scripts/build
      - run: ./scripts/test
  buildall:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build (matrix)
    needs: build
    steps:
      - name: Check build matrix status
        if: ${{ needs.build.result != 'success' }}
        run: exit 1
